# Generated by Django 3.0.1 on 2020-07-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='studentEmail',
        ),
    ]
