# Generated by Django 3.0.1 on 2020-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_remove_userprofile_studentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Due',
            field=models.FloatField(default=0),
        ),
    ]
