# Generated by Django 3.0.1 on 2020-07-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20200725_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Due',
            new_name='academicFee',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hostelFee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otherFee',
            field=models.FloatField(default=0),
        ),
    ]
